<!--
* 注册
* @author （cgt）
* @date 2020/7/30
-->
<!--
* 重置密码
* @author （cgt）
* @date 2020/7/30
-->
<template>
  <div class="flex justify-center contns">
    <div class="text-center">
      <div>
        <img class="margin-bottom logImg" src="../../assets/logo.png" />
      </div>
      <el-form
        ref="addForm"
        :model="form"
        label-position="top"
        :rules="formRules"
        class="margin-bottom conta"
      >
        <el-form-item prop="nation" class="trans">
          <el-select
            style="width: 100%"
            v-model="form.nation"
            placeholder="Nation"
          >
            <el-option
              v-for="item in countryList"
              :key="item.id"
              :label="`+${item.mobileCode}  ${item.en}`"
              :value="item.code"
            >
            </el-option>
          </el-select>
        </el-form-item>
        <el-form-item prop="email" class="trans">
          <el-input v-model="form.email" placeholder="Enter email"></el-input>
        </el-form-item>
        <el-form-item prop="pass" class="trans text-left margin-bottom-lg">
          <el-input
            type="password"
            show-password
            v-model="form.pass"
            placeholder="Enter login password"
          ></el-input>
        </el-form-item>
        <el-form-item prop="checkPass" class="trans margin-bottom">
          <el-input
            type="password"
            show-password
            v-model="form.checkPass"
            placeholder="Enter the login password again"
          ></el-input>
        </el-form-item>
        <el-form-item prop="code" class="trans positRe">
          <div class="blcks" @click="goVer">
            {{ isDisable ? countdown + "s" : "Get verification code" }}
          </div>
          <el-input
            v-model="form.code"
            placeholder="E-mail verification code"
          ></el-input>
        </el-form-item>
        <el-form-item class="trans">
          <el-input
            v-model="form.invitedCode"
            placeholder="Invitation code (optional)"
          ></el-input>
        </el-form-item>
      </el-form>
      <div class="trans conta">
        <el-button v-waves @click="doSve">Register</el-button>
      </div>
      <div
        class="padding-tb-xs margin-bottom-sm pointer text-right fontSize-14"
        @click="$router.push({ name: 'login' })"
      >
        Already have an account to log in directly
      </div>
      <div>
        <el-checkbox v-model="checked" class="coloFFF"
          >I have read and agree to "Privacy Policy" "User
          Agreement"</el-checkbox
        >
      </div>
    </div>
  </div>
</template>

<script>
import api from "@/api";
import md5 from "js-md5";
export default {
  name: "",
  components: {},
  props: {},
  data() {
    var validatePass = (rule, value, callback) => {
      var reg = new RegExp(/[A-Za-z].*[0-9]|[0-9].*[A-Za-z]/);
      if (value.length < 8 || value.length > 20 || !reg.test(value)) {
        callback(
          new Error(
            "The password must be at least 8-20 characters and must contain numbers and letters"
          )
        );
      } else {
        if (this.formRules.checkPass !== "") {
          this.$refs.addForm.validateField("checkPass");
        }
        callback();
      }
    };
    var validatePass2 = (rule, value, callback) => {
      if (value === "") {
        callback(new Error("Please enter the password again"));
      } else if (value !== this.form.pass) {
        callback(new Error("The two passwords are inconsistent!"));
      } else {
        callback();
      }
    };
    var obj = {
      required: true,
      message: "*is required, please fill in the following carefully",
      trigger: "blur",
    };
    return {
      isDisable: false,
      countdown: 90,
      checked: false,
      form: {
        nation: "",
        email: "",
        pass: "",
        checkPass: "",
        code: "",
        invitedCode: "",
      },
      countryList: [],
      formRules: {
        email: [
          { ...obj },
          {
            type: "email",
            message: "Please enter the correct email address",
            trigger: ["blur", "change"],
          },
        ],
        pass: [{ validator: validatePass, trigger: "blur" }],
        checkPass: [{ validator: validatePass2, trigger: "blur" }],
        code: { ...obj },
        nation: { ...obj },
      },
    };
  },
  computed: {},
  methods: {
    doSve() {
      this.$refs.addForm.validate((valid) => {
        if (valid) {
          this.register();
        }
      });
    },
    goVer() {
      if (this.isDisable) {
        return;
      }
      this.sendRegistCode();
    },

    //获取国家区号列表
    async getCountryList() {
      let result = await api.$getCountryList({});
      if (result.errorCode == null) {
        this.countryList = result.data;
      }
    },

    //发送注册验证码
    async sendRegistCode() {
      let { nation, email } = this.form;
      let result = await api.$sendRegistCode({
        areaCode: nation,
        account: email,
      });
      if (result.errorCode == null) {
        this.$message({
          message: "Send Message Success!",
          type: "success",
        });

        this.succesIng();
      }
    },

    /*
   nation: "",
        email: "",
        pass: "",
        checkPass: "",
        code: "",
        invitedCode: "",
*/

    //注册
    async register() {
      let { nation, email, pass, code, invitedCode } = this.form;
      let result = await api.$register({
        areaCode: nation,
        account: email,
        password: md5("qwxioixascrwqd" + pass),
        verifyCode: code,
        inviteCode: invitedCode,
      });
      if (result.errorCode == null) {
        this.$message({
          message: "Register Success!",
          type: "success",
        });
        this.$router.push("/login");
      }
    },
  },

  created() {
    this.countryList = [
      {
        id: 1,
        code: "AF",
        en: "Afghanistan",
        cn: "阿富汗",
        mobileCode: 93,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 2,
        code: "DZ",
        en: "Algeria",
        cn: "阿尔及利亚",
        mobileCode: 213,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 3,
        code: "AS",
        en: "American Samoa",
        cn: "美属萨摩亚",
        mobileCode: 1684,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 4,
        code: "AD",
        en: "Andorra",
        cn: "安道尔",
        mobileCode: 376,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 5,
        code: "AO",
        en: "Angola",
        cn: "安哥拉",
        mobileCode: 244,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 6,
        code: "AI",
        en: "Anguilla",
        cn: "安圭拉",
        mobileCode: 1264,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 7,
        code: "AQ",
        en: "Antarctica",
        cn: "南极洲",
        mobileCode: 672,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 8,
        code: "AG",
        en: "Antigua & Barbuda",
        cn: "安提瓜和巴布达",
        mobileCode: 1268,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 9,
        code: "AR",
        en: "Argentina",
        cn: "阿根廷",
        mobileCode: 54,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 10,
        code: "AM",
        en: "Armenia",
        cn: "亚美尼亚",
        mobileCode: 374,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 11,
        code: "AW",
        en: "Aruba",
        cn: "阿鲁巴",
        mobileCode: 297,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 12,
        code: "AU",
        en: "Australia",
        cn: "澳大利亚",
        mobileCode: 61,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 13,
        code: "AT",
        en: "Austria",
        cn: "奥地利",
        mobileCode: 43,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 14,
        code: "BH",
        en: "Bahrain",
        cn: "巴林",
        mobileCode: 973,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 15,
        code: "BD",
        en: "Bangladesh",
        cn: "孟加拉",
        mobileCode: 880,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 16,
        code: "BB",
        en: "Barbados",
        cn: "巴巴多斯",
        mobileCode: 1246,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 17,
        code: "BE",
        en: "Belgium",
        cn: "比利时",
        mobileCode: 32,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 18,
        code: "BZ",
        en: "Belize",
        cn: "伯利兹",
        mobileCode: 501,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 19,
        code: "BJ",
        en: "Benin",
        cn: "贝宁",
        mobileCode: 229,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 20,
        code: "BM",
        en: "Bermuda",
        cn: "百慕大",
        mobileCode: 1441,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 21,
        code: "BT",
        en: "Bhutan",
        cn: "不丹",
        mobileCode: 975,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 22,
        code: "BO",
        en: "Bolivia",
        cn: "玻利维亚",
        mobileCode: 591,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 23,
        code: "BW",
        en: "Botswana",
        cn: "博茨瓦纳",
        mobileCode: 267,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 24,
        code: "BR",
        en: "Brazil",
        cn: "巴西",
        mobileCode: 55,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 25,
        code: "IO",
        en: "British Indian Ocean Territory",
        cn: "英属印度洋领地",
        mobileCode: 246,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 26,
        code: "BN",
        en: "Brunei",
        cn: "文莱",
        mobileCode: 673,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 27,
        code: "BG",
        en: "Bulgaria",
        cn: "保加利亚",
        mobileCode: 359,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 28,
        code: "BF",
        en: "Burkina",
        cn: "布基纳法索",
        mobileCode: 226,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 29,
        code: "BI",
        en: "Burundi",
        cn: "布隆迪",
        mobileCode: 257,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 30,
        code: "KH",
        en: "Cambodia",
        cn: "柬埔寨",
        mobileCode: 855,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 31,
        code: "CM",
        en: "Cameroon",
        cn: "喀麦隆",
        mobileCode: 237,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 32,
        code: "CA",
        en: "Canada",
        cn: "加拿大",
        mobileCode: 1,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 33,
        code: "CV",
        en: "Cape Verde",
        cn: "佛得角",
        mobileCode: 238,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 34,
        code: "KY",
        en: "Cayman Islands",
        cn: "开曼群岛",
        mobileCode: 1345,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 35,
        code: "CF",
        en: "Central African Republic",
        cn: "中非",
        mobileCode: 236,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 36,
        code: "TD",
        en: "Chad",
        cn: "乍得",
        mobileCode: 235,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 37,
        code: "CL",
        en: "Chile",
        cn: "智利",
        mobileCode: 56,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 38,
        code: "CN",
        en: "China",
        cn: "中国",
        mobileCode: 86,
        usually: true,
        currencyId: null,
        langId: 1,
      },
      {
        id: 39,
        code: "CX",
        en: "Christmas Island",
        cn: "圣诞岛",
        mobileCode: 61,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 40,
        code: "CC",
        en: "Cocos (Keeling) Islands",
        cn: "科科斯群岛",
        mobileCode: 61,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 41,
        code: "CO",
        en: "Colombia",
        cn: "哥伦比亚",
        mobileCode: 57,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 42,
        code: "CK",
        en: "Cook Islands",
        cn: "库克群岛",
        mobileCode: 682,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 43,
        code: "CR",
        en: "Costa Rica",
        cn: "哥斯达黎加",
        mobileCode: 506,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 44,
        code: "HR",
        en: "Croatia",
        cn: "克罗地亚",
        mobileCode: 385,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 45,
        code: "CW",
        en: "Curacao",
        cn: "库拉索",
        mobileCode: 5999,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 46,
        code: "CY",
        en: "Cyprus",
        cn: "塞浦路斯",
        mobileCode: 357,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 47,
        code: "CZ",
        en: "Czech Republic",
        cn: "捷克",
        mobileCode: 420,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 48,
        code: "DK",
        en: "Denmark",
        cn: "丹麦",
        mobileCode: 45,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 49,
        code: "DJ",
        en: "Djibouti",
        cn: "吉布提",
        mobileCode: 253,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 50,
        code: "DM",
        en: "Dominica",
        cn: "多米尼克",
        mobileCode: 1767,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 51,
        code: "DO",
        en: "Dominican Republic",
        cn: "多米尼加",
        mobileCode: 1849,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 52,
        code: "EC",
        en: "Ecuador",
        cn: "厄瓜多尔",
        mobileCode: 593,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 53,
        code: "EG",
        en: "Egypt",
        cn: "埃及",
        mobileCode: 20,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 54,
        code: "SV",
        en: "El Salvador",
        cn: "萨尔瓦多",
        mobileCode: 503,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 55,
        code: "GQ",
        en: "Equatorial Guinea",
        cn: "赤道几内亚",
        mobileCode: 240,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 56,
        code: "ER",
        en: "Eritrea",
        cn: "厄立特里亚",
        mobileCode: 291,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 57,
        code: "EE",
        en: "Estonia",
        cn: "爱沙尼亚",
        mobileCode: 372,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 58,
        code: "ET",
        en: "Ethiopia",
        cn: "埃塞俄比亚",
        mobileCode: 251,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 59,
        code: "FM",
        en: "Federated States of Micronesia",
        cn: "密克罗尼西亚联邦",
        mobileCode: 691,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 60,
        code: "FJ",
        en: "Fiji",
        cn: "斐济群岛",
        mobileCode: 679,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 61,
        code: "FI",
        en: "Finland",
        cn: "芬兰",
        mobileCode: 358,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 62,
        code: "FR",
        en: "France",
        cn: "法国",
        mobileCode: 33,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 63,
        code: "GF",
        en: "French Guiana",
        cn: "法属圭亚那",
        mobileCode: 594,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 64,
        code: "PF",
        en: "French polynesia",
        cn: "法属波利尼西亚",
        mobileCode: 689,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 65,
        code: "GA",
        en: "Gabon",
        cn: "加蓬",
        mobileCode: 241,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 66,
        code: "GM",
        en: "Gambia",
        cn: "冈比亚",
        mobileCode: 220,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 67,
        code: "GE",
        en: "Georgia",
        cn: "格鲁吉亚",
        mobileCode: 995,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 68,
        code: "DE",
        en: "Germany",
        cn: "德国",
        mobileCode: 49,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 69,
        code: "GH",
        en: "Ghana",
        cn: "加纳",
        mobileCode: 233,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 70,
        code: "GI",
        en: "Gibraltar",
        cn: "直布罗陀",
        mobileCode: 350,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 71,
        code: "GB",
        en: "Great Britain (United Kingdom; England)",
        cn: "英国",
        mobileCode: 44,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 72,
        code: "GR",
        en: "Greece",
        cn: "希腊",
        mobileCode: 30,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 73,
        code: "GL",
        en: "Greenland",
        cn: "格陵兰",
        mobileCode: 299,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 74,
        code: "GD",
        en: "Grenada",
        cn: "格林纳达",
        mobileCode: 1473,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 75,
        code: "GP",
        en: "Guadeloupe",
        cn: "瓜德罗普",
        mobileCode: 590,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 76,
        code: "GU",
        en: "Guam",
        cn: "关岛",
        mobileCode: 1671,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 77,
        code: "GT",
        en: "Guatemala",
        cn: "危地马拉",
        mobileCode: 502,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 78,
        code: "GG",
        en: "Guernsey",
        cn: "根西岛",
        mobileCode: 44,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 79,
        code: "GY",
        en: "Guyana",
        cn: "圭亚那",
        mobileCode: 592,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 80,
        code: "HT",
        en: "Haiti",
        cn: "海地",
        mobileCode: 509,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 81,
        code: "HN",
        en: "Honduras",
        cn: "洪都拉斯",
        mobileCode: 504,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 82,
        code: "HK",
        en: "Hong Kong",
        cn: "中国香港",
        mobileCode: 852,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 83,
        code: "HU",
        en: "Hungary",
        cn: "匈牙利",
        mobileCode: 36,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 84,
        code: "IS",
        en: "Iceland",
        cn: "冰岛",
        mobileCode: 354,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 85,
        code: "IN",
        en: "India",
        cn: "印度",
        mobileCode: 91,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 86,
        code: "ID",
        en: "Indonesia",
        cn: "印尼",
        mobileCode: 62,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 87,
        code: "IE",
        en: "Ireland",
        cn: "爱尔兰",
        mobileCode: 353,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 88,
        code: "IM",
        en: "Isle of Man",
        cn: "马恩岛",
        mobileCode: 441624,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 89,
        code: "IL",
        en: "Israel",
        cn: "以色列",
        mobileCode: 972,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 90,
        code: "IT",
        en: "Italy",
        cn: "意大利",
        mobileCode: 39,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 91,
        code: "JM",
        en: "Jamaica",
        cn: "牙买加",
        mobileCode: 1876,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 92,
        code: "JP",
        en: "Japan",
        cn: "日本",
        mobileCode: 81,
        usually: true,
        currencyId: null,
        langId: 2,
      },
      {
        id: 93,
        code: "JE",
        en: "Jersey",
        cn: "泽西岛",
        mobileCode: 44,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 94,
        code: "JO",
        en: "Jordan",
        cn: "约旦",
        mobileCode: 962,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 95,
        code: "KZ",
        en: "Kazakhstan",
        cn: "哈萨克斯坦",
        mobileCode: 7,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 96,
        code: "KE",
        en: "Kenya",
        cn: "肯尼亚",
        mobileCode: 254,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 97,
        code: "KI",
        en: "Kiribati",
        cn: "基里巴斯",
        mobileCode: 686,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 98,
        code: "XK",
        en: "Kosovo",
        cn: "科索沃",
        mobileCode: 383,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 99,
        code: "KWT",
        en: "Kuwait",
        cn: "科威特",
        mobileCode: 965,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 100,
        code: "KG",
        en: "Kyrgyzstan",
        cn: "吉尔吉斯斯坦",
        mobileCode: 996,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 101,
        code: "LA",
        en: "Laos",
        cn: "老挝",
        mobileCode: 856,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 102,
        code: "LV",
        en: "Latvia",
        cn: "拉脱维亚",
        mobileCode: 371,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 103,
        code: "LB",
        en: "Lebanon",
        cn: "黎巴嫩",
        mobileCode: 961,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 104,
        code: "LY",
        en: "Libya",
        cn: "利比亚",
        mobileCode: 218,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 105,
        code: "LI",
        en: "Liechtenstein",
        cn: "列支敦士登",
        mobileCode: 423,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 106,
        code: "LT",
        en: "Lithuania",
        cn: "立陶宛",
        mobileCode: 370,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 107,
        code: "LU",
        en: "Luxembourg",
        cn: "卢森堡",
        mobileCode: 352,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 108,
        code: "MO",
        en: "Macao",
        cn: "中国澳门",
        mobileCode: 853,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 109,
        code: "MG",
        en: "Madagascar",
        cn: "马达加斯加",
        mobileCode: 261,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 110,
        code: "MW",
        en: "Malawi",
        cn: "马拉维",
        mobileCode: 265,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 111,
        code: "MY",
        en: "Malaysia",
        cn: "马来西亚",
        mobileCode: 60,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 112,
        code: "MV",
        en: "Maldives",
        cn: "马尔代夫",
        mobileCode: 960,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 113,
        code: "MT",
        en: "Malta",
        cn: "马耳他",
        mobileCode: 356,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 114,
        code: "MQ",
        en: "Martinique",
        cn: "马提尼克",
        mobileCode: 596,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 115,
        code: "MR",
        en: "Mauritania",
        cn: "毛里塔尼亚",
        mobileCode: 222,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 116,
        code: "MU",
        en: "Mauritius",
        cn: "毛里求斯",
        mobileCode: 230,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 117,
        code: "MX",
        en: "Mexico",
        cn: "墨西哥",
        mobileCode: 52,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 118,
        code: "MD",
        en: "Moldova",
        cn: "摩尔多瓦",
        mobileCode: 373,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 119,
        code: "MN",
        en: "Mongolia",
        cn: "蒙古国",
        mobileCode: 976,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 120,
        code: "ME",
        en: "Montenegro",
        cn: "黑山",
        mobileCode: 382,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 121,
        code: "MS",
        en: "Montserrat",
        cn: "蒙塞拉特岛",
        mobileCode: 1664,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 122,
        code: "MA",
        en: "Morocco",
        cn: "摩洛哥",
        mobileCode: 212,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 123,
        code: "MZ",
        en: "Mozambique",
        cn: "莫桑比克",
        mobileCode: 258,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 124,
        code: "MM",
        en: "Myanmar",
        cn: "缅甸",
        mobileCode: 95,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 125,
        code: "NA",
        en: "Namibia",
        cn: "纳米比亚",
        mobileCode: 264,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 126,
        code: "NR",
        en: "Nauru",
        cn: "瑙鲁",
        mobileCode: 674,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 127,
        code: "NP",
        en: "Nepal",
        cn: "尼泊尔",
        mobileCode: 977,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 128,
        code: "NL",
        en: "Netherlands",
        cn: "荷兰",
        mobileCode: 31,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 129,
        code: "NCL",
        en: "New Caledonia",
        cn: "新喀里多尼亚",
        mobileCode: 687,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 130,
        code: "NZ",
        en: "New Zealand",
        cn: "新西兰",
        mobileCode: 64,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 131,
        code: "NI",
        en: "Nicaragua",
        cn: "尼加拉瓜",
        mobileCode: 505,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 132,
        code: "NE",
        en: "Niger",
        cn: "尼日尔",
        mobileCode: 227,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 133,
        code: "NG",
        en: "Nigeria",
        cn: "尼日利亚",
        mobileCode: 234,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 134,
        code: "NU",
        en: "Niue",
        cn: "纽埃",
        mobileCode: 683,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 135,
        code: "NF",
        en: "Norfolk Island",
        cn: "诺福克岛",
        mobileCode: 672,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 136,
        code: "NO",
        en: "Norway",
        cn: "挪威",
        mobileCode: 47,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 137,
        code: "PK",
        en: "Pakistan",
        cn: "巴基斯坦",
        mobileCode: 92,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 138,
        code: "PW",
        en: "Palau",
        cn: "帕劳",
        mobileCode: 680,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 139,
        code: "PS",
        en: "Palestinian territories",
        cn: "巴勒斯坦",
        mobileCode: 970,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 140,
        code: "PA",
        en: "Panama",
        cn: "巴拿马",
        mobileCode: 507,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 141,
        code: "PG",
        en: "Papua New Guinea",
        cn: "巴布亚新几内亚",
        mobileCode: 675,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 142,
        code: "PY",
        en: "Paraguay",
        cn: "巴拉圭",
        mobileCode: 595,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 143,
        code: "PE",
        en: "Peru",
        cn: "秘鲁",
        mobileCode: 51,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 144,
        code: "PN",
        en: "Pitcairn Islands",
        cn: "皮特凯恩群岛",
        mobileCode: 64,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 145,
        code: "PL",
        en: "Poland",
        cn: "波兰",
        mobileCode: 48,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 146,
        code: "PT",
        en: "Portugal",
        cn: "葡萄牙",
        mobileCode: 351,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 147,
        code: "PR",
        en: "Puerto Rico",
        cn: "波多黎各",
        mobileCode: 1787,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 148,
        code: "QA",
        en: "Qatar",
        cn: "卡塔尔",
        mobileCode: 974,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 149,
        code: "BLR",
        en: "Republic of Belarus",
        cn: "白俄罗斯共和国",
        mobileCode: 375,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 150,
        code: "MKD",
        en: "Republic of North Macedonia",
        cn: "北马其顿",
        mobileCode: 389,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 151,
        code: "RO",
        en: "Romania",
        cn: "罗马尼亚",
        mobileCode: 40,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 152,
        code: "RU",
        en: "Russian Federation",
        cn: "俄罗斯",
        mobileCode: 7,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 153,
        code: "RW",
        en: "Rwanda",
        cn: "卢旺达",
        mobileCode: 250,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 154,
        code: "RE",
        en: "Réunion",
        cn: "留尼汪",
        mobileCode: 262,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 155,
        code: "MF",
        en: "Saint Martin (France)",
        cn: "法属圣马丁",
        mobileCode: 590,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 156,
        code: "PM",
        en: "Saint-Pierre and Miquelon",
        cn: "圣皮埃尔和密克隆",
        mobileCode: 508,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 157,
        code: "WS",
        en: "Samoa",
        cn: "萨摩亚",
        mobileCode: 685,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 158,
        code: "SM",
        en: "San Marino",
        cn: "圣马力诺",
        mobileCode: 378,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 159,
        code: "SA",
        en: "Saudi Arabia",
        cn: "沙特阿拉伯",
        mobileCode: 966,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 160,
        code: "SN",
        en: "Senegal",
        cn: "塞内加尔",
        mobileCode: 221,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 161,
        code: "SC",
        en: "Seychelles",
        cn: "塞舌尔",
        mobileCode: 248,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 162,
        code: "SL",
        en: "Sierra Leone",
        cn: "塞拉利昂",
        mobileCode: 232,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 164,
        code: "SX",
        en: "Sint Maarten",
        cn: "荷属圣马丁",
        mobileCode: 1721,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 165,
        code: "SK",
        en: "Slovakia",
        cn: "斯洛伐克",
        mobileCode: 421,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 166,
        code: "SI",
        en: "Slovenia",
        cn: "斯洛文尼亚",
        mobileCode: 386,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 167,
        code: "SB",
        en: "Solomon Islands",
        cn: "所罗门群岛",
        mobileCode: 677,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 168,
        code: "SO",
        en: "Somalia",
        cn: "索马里",
        mobileCode: 252,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 169,
        code: "ZA",
        en: "South Africa",
        cn: "南非",
        mobileCode: 27,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 170,
        code: "KR",
        en: "South Korea",
        cn: "韩国",
        mobileCode: 82,
        usually: true,
        currencyId: null,
        langId: 2,
      },
      {
        id: 171,
        code: "ES",
        en: "Spain",
        cn: "西班牙",
        mobileCode: 34,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 172,
        code: "LK",
        en: "Sri Lanka",
        cn: "斯里兰卡",
        mobileCode: 94,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 173,
        code: "SH",
        en: "St. Helena & Dependencies",
        cn: "圣赫勒拿",
        mobileCode: 290,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 174,
        code: "KN",
        en: "St. Kitts & Nevis",
        cn: "圣基茨和尼维斯",
        mobileCode: 1869,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 175,
        code: "LC",
        en: "St. Lucia",
        cn: "圣卢西亚",
        mobileCode: 1758,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 176,
        code: "VC",
        en: "St. Vincent & the Grenadines",
        cn: "圣文森特和格林纳丁斯",
        mobileCode: 1784,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 177,
        code: "SR",
        en: "Suriname",
        cn: "苏里南",
        mobileCode: 597,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 178,
        code: "SZ",
        en: "Swaziland",
        cn: "斯威士兰",
        mobileCode: 268,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 179,
        code: "SE",
        en: "Sweden",
        cn: "瑞典",
        mobileCode: 46,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 180,
        code: "CH",
        en: "Switzerland",
        cn: "瑞士",
        mobileCode: 41,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 181,
        code: "TW",
        en: "Taiwan",
        cn: "中国台湾",
        mobileCode: 886,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 182,
        code: "TJ",
        en: "Tajikistan",
        cn: "塔吉克斯坦",
        mobileCode: 992,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 183,
        code: "TZ",
        en: "Tanzania",
        cn: "坦桑尼亚",
        mobileCode: 255,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 184,
        code: "TH",
        en: "Thailand",
        cn: "泰国",
        mobileCode: 66,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 185,
        code: "BS",
        en: "The Bahamas",
        cn: "巴哈马",
        mobileCode: 1242,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 186,
        code: "VG",
        en: "The British Virgin Islands",
        cn: "英属维尔京群岛",
        mobileCode: 1284,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 187,
        code: "PH",
        en: "The Philippines",
        cn: "菲律宾",
        mobileCode: 63,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 188,
        code: "AZE",
        en: "The Republic of Azerbaijan",
        cn: "阿塞拜疆",
        mobileCode: 994,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 189,
        code: "SRB",
        en: "The Republic of Serbia",
        cn: "塞尔维亚",
        mobileCode: 381,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 190,
        code: "MH",
        en: "The Republic of the Marshall Islands",
        cn: "马绍尔群岛",
        mobileCode: 692,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 191,
        code: "EH",
        en: "The Sahrawi Arab Democratic Republic",
        cn: "西撒哈拉",
        mobileCode: 21228,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 192,
        code: "TG",
        en: "Togo",
        cn: "多哥",
        mobileCode: 228,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 193,
        code: "TK",
        en: "Tokelau",
        cn: "托克劳",
        mobileCode: 690,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 194,
        code: "TO",
        en: "Tonga",
        cn: "汤加",
        mobileCode: 676,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 195,
        code: "TT",
        en: "Trinidad & Tobago",
        cn: "特立尼达和多巴哥",
        mobileCode: 1868,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 196,
        code: "TN",
        en: "Tunisia",
        cn: "突尼斯",
        mobileCode: 216,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 197,
        code: "TR",
        en: "Turkey",
        cn: "土耳其",
        mobileCode: 90,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 198,
        code: "TKM",
        en: "Turkmenistan",
        cn: "土库曼斯坦",
        mobileCode: 993,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 199,
        code: "TV",
        en: "Tuvalu",
        cn: "图瓦卢",
        mobileCode: 688,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 200,
        code: "UG",
        en: "Uganda",
        cn: "乌干达",
        mobileCode: 256,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 201,
        code: "UA",
        en: "Ukraine",
        cn: "乌克兰",
        mobileCode: 380,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 202,
        code: "AE",
        en: "United Arab Emirates",
        cn: "阿联酋",
        mobileCode: 971,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 203,
        code: "UY",
        en: "Uruguay",
        cn: "乌拉圭",
        mobileCode: 598,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 204,
        code: "UZ",
        en: "Uzbekistan",
        cn: "乌兹别克斯坦",
        mobileCode: 998,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 205,
        code: "VU",
        en: "Vanuatu",
        cn: "瓦努阿图",
        mobileCode: 678,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 206,
        code: "VA",
        en: "Vatican City (The Holy See)",
        cn: "梵蒂冈",
        mobileCode: 379,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 207,
        code: "VE",
        en: "Venezuela",
        cn: "委内瑞拉",
        mobileCode: 58,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 208,
        code: "VN",
        en: "Vietnam",
        cn: "越南",
        mobileCode: 84,
        usually: true,
        currencyId: null,
        langId: 2,
      },
      {
        id: 209,
        code: "WF",
        en: "Wallis and Futuna",
        cn: "瓦利斯和富图纳",
        mobileCode: 681,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 210,
        code: "YE",
        en: "Yemen",
        cn: "也门",
        mobileCode: 967,
        usually: false,
        currencyId: null,
        langId: 2,
      },
      {
        id: 211,
        code: "ZM",
        en: "Zambia",
        cn: "赞比亚",
        mobileCode: 260,
        usually: false,
        currencyId: null,
        langId: 2,
      },
    ];
    this.countryList = Object.freeze(this.countryList);
  },
  mounted() {
    this.getCountryList();
  },
};
</script>
<style lang="scss" scoped>
.contns {
  color: #ffffff;
  width: 100%;
  height: 100vh;
  background: url(../../assets/backs.png) no-repeat;
  background-size: cover;
  padding-top: 140px;
  .conta {
    width: 400px;
    margin-left: auto;
    margin-right: auto;
    .logImg {
      width: 60px;
    }
  }
}
</style>
